
[app]
# 项目运行级别 debug test production
mode="debug"
token="1234567890asdfgh"

[http]
# http 运行的端口
addr=":8080"

[db]
# 数据库类型
db_type="mysql"
# 数据库连接信息
dsn="root:123456@tcp(127.0.0.1:3306)/test?charset=utf8mb4"
# 设置最大打开的连接数
open_max=1000
# 设置闲置的连接数
idle_max=10

[log]
# 日志文件路径
path="./all.log"
# 设置日志级别 debug  info  error
level="debug"
# 每个日志文件保存大小，为M，默认 100M
max_size=10
# 保留 N 个备份，默认不限
max_backup=10
# 保留 N 天，默认不限
max_age=7
