app:
  # 项目名
  name: im-server
  # debug release
  mode: debug
  # ip (默认: 0.0.0.0)
  IP: 0.0.0.0
  # 端口 (默认: 5050)
  port: 5050
  pid: ./im-server.pid

logs:
  # 日志文件路径: 【当为空时是 控制台 输出】【当不为空(./logs.log)时是 文件 输出】
  path:
  # 日志级别 debug  info  error(默认: debug)
  logLevel: debug
  # 每个日志文件保存大小M(默认: 0 为不限)
  maxSize: 10
  # 保留 N 个备份(默认: 0 为不限)
  maxBackup: 10
  # 保留 N 天(默认: 0 为不限)
  maxAge: 7

websocket:
  # 读超时(秒)(默认: 20)，同时也是心跳超时
  readTime: 20
  # 写超时(秒)(默认: 3)
  writeTime: 3

mysql:
  dsn: root:123456@tcp(127.0.0.1:3306)/test?charset=utf8mb4&parseTime=True&loc=Local
  # 设置空闲连接池中连接的最大数量
  maxIdleConn: 5
  # 设置打开数据库连接的最大数量
  maxOpenConn: 100
  # 设置了连接可复用的最大时间(单位：分)
  connMaxLifetime: 30

# 支持 单机、分布式集群
redis:
  # 选择 N 号数据库
  DBNum: 0
  password:
  # 当节点只有一个视为单机
  nodes:
    - 127.0.0.1:6379

jwt:
  secretKey: W6VjDud2W1kMG3BicbMNlGgI4ZfcoHtMGLWr
  # 过期时长(秒)
  expTime: 2592000
