// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.12.3
// source: cmd_int.proto

package protoapi

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CMD int32

const (
	// 未知
	CMD_C_UNKNOWN CMD = 0
	// 错误
	CMD_C_ERROR CMD = 1
	// 登录
	CMD_C_LOGIN_REQUEST  CMD = 5
	CMD_C_LOGIN_RESPONSE CMD = 6
)

// Enum value maps for CMD.
var (
	CMD_name = map[int32]string{
		0: "C_UNKNOWN",
		1: "C_ERROR",
		5: "C_LOGIN_REQUEST",
		6: "C_LOGIN_RESPONSE",
	}
	CMD_value = map[string]int32{
		"C_UNKNOWN":        0,
		"C_ERROR":          1,
		"C_LOGIN_REQUEST":  5,
		"C_LOGIN_RESPONSE": 6,
	}
)

func (x CMD) Enum() *CMD {
	p := new(CMD)
	*p = x
	return p
}

func (x CMD) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CMD) Descriptor() protoreflect.EnumDescriptor {
	return file_cmd_int_proto_enumTypes[0].Descriptor()
}

func (CMD) Type() protoreflect.EnumType {
	return &file_cmd_int_proto_enumTypes[0]
}

func (x CMD) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CMD.Descriptor instead.
func (CMD) EnumDescriptor() ([]byte, []int) {
	return file_cmd_int_proto_rawDescGZIP(), []int{0}
}

var File_cmd_int_proto protoreflect.FileDescriptor

var file_cmd_int_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x6d, 0x64, 0x5f, 0x69, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69, 0x2a, 0x4c, 0x0a, 0x03, 0x43, 0x4d, 0x44,
	0x12, 0x0d, 0x0a, 0x09, 0x43, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x43, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f,
	0x43, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10,
	0x05, 0x12, 0x14, 0x0a, 0x10, 0x43, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x52, 0x45, 0x53,
	0x50, 0x4f, 0x4e, 0x53, 0x45, 0x10, 0x06, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x61, 0x69, 0x78, 0x68, 0x65, 0x2f, 0x6c, 0x61, 0x69,
	0x78, 0x68, 0x65, 0x2d, 0x61, 0x70, 0x70, 0x2f, 0x6c, 0x61, 0x69, 0x78, 0x68, 0x65, 0x2d, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_int_proto_rawDescOnce sync.Once
	file_cmd_int_proto_rawDescData = file_cmd_int_proto_rawDesc
)

func file_cmd_int_proto_rawDescGZIP() []byte {
	file_cmd_int_proto_rawDescOnce.Do(func() {
		file_cmd_int_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_int_proto_rawDescData)
	})
	return file_cmd_int_proto_rawDescData
}

var file_cmd_int_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cmd_int_proto_goTypes = []interface{}{
	(CMD)(0), // 0: protoapi.CMD
}
var file_cmd_int_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_int_proto_init() }
func file_cmd_int_proto_init() {
	if File_cmd_int_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_int_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_int_proto_goTypes,
		DependencyIndexes: file_cmd_int_proto_depIdxs,
		EnumInfos:         file_cmd_int_proto_enumTypes,
	}.Build()
	File_cmd_int_proto = out.File
	file_cmd_int_proto_rawDesc = nil
	file_cmd_int_proto_goTypes = nil
	file_cmd_int_proto_depIdxs = nil
}
