// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: dialog_content.proto

package protoim

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息会话内容
type DialogContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnreadCount int32           `protobuf:"varint,1,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"` // 未读数
	Content     *MessageContent `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                             // 消息内容
	UserBase    *UserBaseInfo   `protobuf:"bytes,3,opt,name=user_base,json=userBase,proto3" json:"user_base,omitempty"`           // 用户基本信息
	GroupBase   *GroupBaseInfo  `protobuf:"bytes,4,opt,name=group_base,json=groupBase,proto3" json:"group_base,omitempty"`        // 群的基本信息
}

func (x *DialogContent) Reset() {
	*x = DialogContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dialog_content_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialogContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialogContent) ProtoMessage() {}

func (x *DialogContent) ProtoReflect() protoreflect.Message {
	mi := &file_dialog_content_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialogContent.ProtoReflect.Descriptor instead.
func (*DialogContent) Descriptor() ([]byte, []int) {
	return file_dialog_content_proto_rawDescGZIP(), []int{0}
}

func (x *DialogContent) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *DialogContent) GetContent() *MessageContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *DialogContent) GetUserBase() *UserBaseInfo {
	if x != nil {
		return x.UserBase
	}
	return nil
}

func (x *DialogContent) GetGroupBase() *GroupBaseInfo {
	if x != nil {
		return x.GroupBase
	}
	return nil
}

var File_dialog_content_proto protoreflect.FileDescriptor

var file_dialog_content_proto_rawDesc = []byte{
	0x0a, 0x14, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6d, 0x1a,
	0x15, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x62, 0x61, 0x73,
	0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xd0, 0x01, 0x0a, 0x0d, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x75, 0x6e, 0x72,
	0x65, 0x61, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x31, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x69, 0x6d, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x32, 0x0a, 0x09, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6d, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x73,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x12,
	0x35, 0x0a, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6d, 0x2e, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x42, 0x61, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x69, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dialog_content_proto_rawDescOnce sync.Once
	file_dialog_content_proto_rawDescData = file_dialog_content_proto_rawDesc
)

func file_dialog_content_proto_rawDescGZIP() []byte {
	file_dialog_content_proto_rawDescOnce.Do(func() {
		file_dialog_content_proto_rawDescData = protoimpl.X.CompressGZIP(file_dialog_content_proto_rawDescData)
	})
	return file_dialog_content_proto_rawDescData
}

var file_dialog_content_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dialog_content_proto_goTypes = []interface{}{
	(*DialogContent)(nil),  // 0: protoim.DialogContent
	(*MessageContent)(nil), // 1: protoim.MessageContent
	(*UserBaseInfo)(nil),   // 2: protoim.UserBaseInfo
	(*GroupBaseInfo)(nil),  // 3: protoim.GroupBaseInfo
}
var file_dialog_content_proto_depIdxs = []int32{
	1, // 0: protoim.DialogContent.content:type_name -> protoim.MessageContent
	2, // 1: protoim.DialogContent.user_base:type_name -> protoim.UserBaseInfo
	3, // 2: protoim.DialogContent.group_base:type_name -> protoim.GroupBaseInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_dialog_content_proto_init() }
func file_dialog_content_proto_init() {
	if File_dialog_content_proto != nil {
		return
	}
	file_message_content_proto_init()
	file_user_base_info_proto_init()
	file_group_base_info_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_dialog_content_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DialogContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dialog_content_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dialog_content_proto_goTypes,
		DependencyIndexes: file_dialog_content_proto_depIdxs,
		MessageInfos:      file_dialog_content_proto_msgTypes,
	}.Build()
	File_dialog_content_proto = out.File
	file_dialog_content_proto_rawDesc = nil
	file_dialog_content_proto_goTypes = nil
	file_dialog_content_proto_depIdxs = nil
}
