// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: e.proto

package protoim

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 错误指令类型
type E int32

const (
	E_UnknownError     E = 0  // 未知错误
	E_RouteNotExist    E = 1  // 路由不存在
	E_ServerError      E = 2  // 系统错误
	E_NotLogin         E = 3  // 未登录
	E_ParameterError   E = 4  // 参数错误
	E_DbNotData        E = 5  // 没有数据
	E_DbSelectError    E = 6  // 数据查询错误
	E_DbInsertError    E = 7  // 数据添加错误
	E_DbDeleteError    E = 8  // 数据删除错误
	E_DbUpateError     E = 9  // 数据更新错误
	E_DbOperationError E = 10 // 数据操作错误
)

// Enum value maps for E.
var (
	E_name = map[int32]string{
		0:  "UnknownError",
		1:  "RouteNotExist",
		2:  "ServerError",
		3:  "NotLogin",
		4:  "ParameterError",
		5:  "DbNotData",
		6:  "DbSelectError",
		7:  "DbInsertError",
		8:  "DbDeleteError",
		9:  "DbUpateError",
		10: "DbOperationError",
	}
	E_value = map[string]int32{
		"UnknownError":     0,
		"RouteNotExist":    1,
		"ServerError":      2,
		"NotLogin":         3,
		"ParameterError":   4,
		"DbNotData":        5,
		"DbSelectError":    6,
		"DbInsertError":    7,
		"DbDeleteError":    8,
		"DbUpateError":     9,
		"DbOperationError": 10,
	}
)

func (x E) Enum() *E {
	p := new(E)
	*p = x
	return p
}

func (x E) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (E) Descriptor() protoreflect.EnumDescriptor {
	return file_e_proto_enumTypes[0].Descriptor()
}

func (E) Type() protoreflect.EnumType {
	return &file_e_proto_enumTypes[0]
}

func (x E) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use E.Descriptor instead.
func (E) EnumDescriptor() ([]byte, []int) {
	return file_e_proto_rawDescGZIP(), []int{0}
}

var File_e_proto protoreflect.FileDescriptor

var file_e_proto_rawDesc = []byte{
	0x0a, 0x07, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x69, 0x6d, 0x2a, 0xcb, 0x01, 0x0a, 0x01, 0x45, 0x12, 0x10, 0x0a, 0x0c, 0x55, 0x6e, 0x6b, 0x6e,
	0x6f, 0x77, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x10, 0x01, 0x12, 0x0f, 0x0a,
	0x0b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x02, 0x12, 0x0c,
	0x0a, 0x08, 0x4e, 0x6f, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x04,
	0x12, 0x0d, 0x0a, 0x09, 0x44, 0x62, 0x4e, 0x6f, 0x74, 0x44, 0x61, 0x74, 0x61, 0x10, 0x05, 0x12,
	0x11, 0x0a, 0x0d, 0x44, 0x62, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x10, 0x06, 0x12, 0x11, 0x0a, 0x0d, 0x44, 0x62, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x10, 0x07, 0x12, 0x11, 0x0a, 0x0d, 0x44, 0x62, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x08, 0x12, 0x10, 0x0a, 0x0c, 0x44, 0x62, 0x55, 0x70,
	0x61, 0x74, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x09, 0x12, 0x14, 0x0a, 0x10, 0x44, 0x62,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x0a,
	0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6d, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_e_proto_rawDescOnce sync.Once
	file_e_proto_rawDescData = file_e_proto_rawDesc
)

func file_e_proto_rawDescGZIP() []byte {
	file_e_proto_rawDescOnce.Do(func() {
		file_e_proto_rawDescData = protoimpl.X.CompressGZIP(file_e_proto_rawDescData)
	})
	return file_e_proto_rawDescData
}

var file_e_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_e_proto_goTypes = []interface{}{
	(E)(0), // 0: protoim.E
}
var file_e_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_e_proto_init() }
func file_e_proto_init() {
	if File_e_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_e_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_e_proto_goTypes,
		DependencyIndexes: file_e_proto_depIdxs,
		EnumInfos:         file_e_proto_enumTypes,
	}.Build()
	File_e_proto = out.File
	file_e_proto_rawDesc = nil
	file_e_proto_goTypes = nil
	file_e_proto_depIdxs = nil
}
