// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: error_type.proto

package protoim

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 错误类型
type ErrorType int32

const (
	ErrorType_E_UNKNOWN         ErrorType = 0  // 未知错误
	ErrorType_E_SERVER          ErrorType = 1  // 服务器错误
	ErrorType_E_WRITE_TIMEOUT   ErrorType = 2  // 服务器读超时
	ErrorType_E_READ_TIMEOUT    ErrorType = 3  // 服务器写超时
	ErrorType_E_ROUTE_NOT_EXIST ErrorType = 4  // 路由不存在
	ErrorType_E_DECODE          ErrorType = 5  // 解码code失败
	ErrorType_E_ENCODE          ErrorType = 6  // 编码code失败
	ErrorType_E_NOT_LOGIN       ErrorType = 7  // 未登录
	ErrorType_E_PARAMETER       ErrorType = 8  // 参数错误
	ErrorType_E_DB_NOT_DATA     ErrorType = 9  // 没有数据
	ErrorType_E_DB_SELECT       ErrorType = 10 // 数据查询错误
	ErrorType_E_DB_INSERT       ErrorType = 11 // 数据添加错误
	ErrorType_E_DB_DELETE       ErrorType = 12 // 数据删除错误
	ErrorType_E_DB_UPATE        ErrorType = 13 // 数据更新错误
	ErrorType_E_DB_OPERATION    ErrorType = 14 // 数据操作错误
)

// Enum value maps for ErrorType.
var (
	ErrorType_name = map[int32]string{
		0:  "E_UNKNOWN",
		1:  "E_SERVER",
		2:  "E_WRITE_TIMEOUT",
		3:  "E_READ_TIMEOUT",
		4:  "E_ROUTE_NOT_EXIST",
		5:  "E_DECODE",
		6:  "E_ENCODE",
		7:  "E_NOT_LOGIN",
		8:  "E_PARAMETER",
		9:  "E_DB_NOT_DATA",
		10: "E_DB_SELECT",
		11: "E_DB_INSERT",
		12: "E_DB_DELETE",
		13: "E_DB_UPATE",
		14: "E_DB_OPERATION",
	}
	ErrorType_value = map[string]int32{
		"E_UNKNOWN":         0,
		"E_SERVER":          1,
		"E_WRITE_TIMEOUT":   2,
		"E_READ_TIMEOUT":    3,
		"E_ROUTE_NOT_EXIST": 4,
		"E_DECODE":          5,
		"E_ENCODE":          6,
		"E_NOT_LOGIN":       7,
		"E_PARAMETER":       8,
		"E_DB_NOT_DATA":     9,
		"E_DB_SELECT":       10,
		"E_DB_INSERT":       11,
		"E_DB_DELETE":       12,
		"E_DB_UPATE":        13,
		"E_DB_OPERATION":    14,
	}
)

func (x ErrorType) Enum() *ErrorType {
	p := new(ErrorType)
	*p = x
	return p
}

func (x ErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_error_type_proto_enumTypes[0].Descriptor()
}

func (ErrorType) Type() protoreflect.EnumType {
	return &file_error_type_proto_enumTypes[0]
}

func (x ErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorType.Descriptor instead.
func (ErrorType) EnumDescriptor() ([]byte, []int) {
	return file_error_type_proto_rawDescGZIP(), []int{0}
}

var File_error_type_proto protoreflect.FileDescriptor

var file_error_type_proto_rawDesc = []byte{
	0x0a, 0x10, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6d, 0x2a, 0x90, 0x02, 0x0a, 0x09,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x45, 0x5f, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x45, 0x5f, 0x53, 0x45,
	0x52, 0x56, 0x45, 0x52, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x5f, 0x57, 0x52, 0x49, 0x54,
	0x45, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x4f, 0x55, 0x54, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x45,
	0x5f, 0x52, 0x45, 0x41, 0x44, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x4f, 0x55, 0x54, 0x10, 0x03, 0x12,
	0x15, 0x0a, 0x11, 0x45, 0x5f, 0x52, 0x4f, 0x55, 0x54, 0x45, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x45,
	0x58, 0x49, 0x53, 0x54, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x45, 0x5f, 0x44, 0x45, 0x43, 0x4f,
	0x44, 0x45, 0x10, 0x05, 0x12, 0x0c, 0x0a, 0x08, 0x45, 0x5f, 0x45, 0x4e, 0x43, 0x4f, 0x44, 0x45,
	0x10, 0x06, 0x12, 0x0f, 0x0a, 0x0b, 0x45, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x4c, 0x4f, 0x47, 0x49,
	0x4e, 0x10, 0x07, 0x12, 0x0f, 0x0a, 0x0b, 0x45, 0x5f, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x45, 0x54,
	0x45, 0x52, 0x10, 0x08, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x5f, 0x44, 0x42, 0x5f, 0x4e, 0x4f, 0x54,
	0x5f, 0x44, 0x41, 0x54, 0x41, 0x10, 0x09, 0x12, 0x0f, 0x0a, 0x0b, 0x45, 0x5f, 0x44, 0x42, 0x5f,
	0x53, 0x45, 0x4c, 0x45, 0x43, 0x54, 0x10, 0x0a, 0x12, 0x0f, 0x0a, 0x0b, 0x45, 0x5f, 0x44, 0x42,
	0x5f, 0x49, 0x4e, 0x53, 0x45, 0x52, 0x54, 0x10, 0x0b, 0x12, 0x0f, 0x0a, 0x0b, 0x45, 0x5f, 0x44,
	0x42, 0x5f, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x0c, 0x12, 0x0e, 0x0a, 0x0a, 0x45, 0x5f,
	0x44, 0x42, 0x5f, 0x55, 0x50, 0x41, 0x54, 0x45, 0x10, 0x0d, 0x12, 0x12, 0x0a, 0x0e, 0x45, 0x5f,
	0x44, 0x42, 0x5f, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x0e, 0x42, 0x0c,
	0x5a, 0x0a, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6d, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_error_type_proto_rawDescOnce sync.Once
	file_error_type_proto_rawDescData = file_error_type_proto_rawDesc
)

func file_error_type_proto_rawDescGZIP() []byte {
	file_error_type_proto_rawDescOnce.Do(func() {
		file_error_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_error_type_proto_rawDescData)
	})
	return file_error_type_proto_rawDescData
}

var file_error_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_error_type_proto_goTypes = []interface{}{
	(ErrorType)(0), // 0: protoim.ErrorType
}
var file_error_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_error_type_proto_init() }
func file_error_type_proto_init() {
	if File_error_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_error_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_error_type_proto_goTypes,
		DependencyIndexes: file_error_type_proto_depIdxs,
		EnumInfos:         file_error_type_proto_enumTypes,
	}.Build()
	File_error_type_proto = out.File
	file_error_type_proto_rawDesc = nil
	file_error_type_proto_goTypes = nil
	file_error_type_proto_depIdxs = nil
}
