// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: message_feedback.proto

package protoim

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息相关-反馈(客户端发送给服务端接收后响应接收该消息，则反)
type MessageFeedback struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConversationId string `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // 会话ID( {user_id}_{to_id} )
	MsgId          string `protobuf:"bytes,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`                            // 消息ID(服务端生成)
	LocalMsgId     string `protobuf:"bytes,3,opt,name=local_msg_id,json=localMsgId,proto3" json:"local_msg_id,omitempty"`           // 客户端本地的消息ID(用于客户校验)(客户端生成)
}

func (x *MessageFeedback) Reset() {
	*x = MessageFeedback{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_feedback_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageFeedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageFeedback) ProtoMessage() {}

func (x *MessageFeedback) ProtoReflect() protoreflect.Message {
	mi := &file_message_feedback_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageFeedback.ProtoReflect.Descriptor instead.
func (*MessageFeedback) Descriptor() ([]byte, []int) {
	return file_message_feedback_proto_rawDescGZIP(), []int{0}
}

func (x *MessageFeedback) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessageFeedback) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *MessageFeedback) GetLocalMsgId() string {
	if x != nil {
		return x.LocalMsgId
	}
	return ""
}

var File_message_feedback_proto protoreflect.FileDescriptor

var file_message_feedback_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x62, 0x61,
	0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69,
	0x6d, 0x22, 0x73, 0x0a, 0x0f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x46, 0x65, 0x65, 0x64,
	0x62, 0x61, 0x63, 0x6b, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63,
	0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x15, 0x0a,
	0x06, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d,
	0x73, 0x67, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x6d, 0x73,
	0x67, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x6f, 0x63, 0x61,
	0x6c, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x69, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_feedback_proto_rawDescOnce sync.Once
	file_message_feedback_proto_rawDescData = file_message_feedback_proto_rawDesc
)

func file_message_feedback_proto_rawDescGZIP() []byte {
	file_message_feedback_proto_rawDescOnce.Do(func() {
		file_message_feedback_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_feedback_proto_rawDescData)
	})
	return file_message_feedback_proto_rawDescData
}

var file_message_feedback_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_feedback_proto_goTypes = []interface{}{
	(*MessageFeedback)(nil), // 0: protoim.MessageFeedback
}
var file_message_feedback_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_feedback_proto_init() }
func file_message_feedback_proto_init() {
	if File_message_feedback_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_feedback_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageFeedback); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_feedback_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_feedback_proto_goTypes,
		DependencyIndexes: file_message_feedback_proto_depIdxs,
		MessageInfos:      file_message_feedback_proto_msgTypes,
	}.Build()
	File_message_feedback_proto = out.File
	file_message_feedback_proto_rawDesc = nil
	file_message_feedback_proto_goTypes = nil
	file_message_feedback_proto_depIdxs = nil
}
