// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: message_feedback.proto

package protoim

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 反馈消息-响应
type MessageFeedback struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DialogId       string              `protobuf:"bytes,1,opt,name=dialog_id,json=dialogId,proto3" json:"dialog_id,omitempty"`                                                       // 会话ID( d_{user_id}_{chat_type}_{to_id} )
	MessageId      string              `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`                                                    // 消息ID( m_{xxx} )(服务端生成)
	FromId         string              `protobuf:"bytes,3,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`                                                             // 发送者(用户ID)
	ToId           string              `protobuf:"bytes,4,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`                                                                   // 接收者(用户ID/群ID)
	Pts            int32               `protobuf:"varint,5,opt,name=pts,proto3" json:"pts,omitempty"`                                                                                // 当前会话的序列ID(可用于排序)(唯一值)(服务端生成)
	ChatTypeId     ChatType            `protobuf:"varint,6,opt,name=chat_type_id,json=chatTypeId,proto3,enum=protoim.ChatType" json:"chat_type_id,omitempty"`                        // 私聊还是群聊
	MessageTypeId  MessageType         `protobuf:"varint,7,opt,name=message_type_id,json=messageTypeId,proto3,enum=protoim.MessageType" json:"message_type_id,omitempty"`            // 消息类型
	FeedbackTypeId MessageFeedbackType `protobuf:"varint,8,opt,name=feedback_type_id,json=feedbackTypeId,proto3,enum=protoim.MessageFeedbackType" json:"feedback_type_id,omitempty"` // 反馈消息类型
}

func (x *MessageFeedback) Reset() {
	*x = MessageFeedback{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_feedback_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageFeedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageFeedback) ProtoMessage() {}

func (x *MessageFeedback) ProtoReflect() protoreflect.Message {
	mi := &file_message_feedback_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageFeedback.ProtoReflect.Descriptor instead.
func (*MessageFeedback) Descriptor() ([]byte, []int) {
	return file_message_feedback_proto_rawDescGZIP(), []int{0}
}

func (x *MessageFeedback) GetDialogId() string {
	if x != nil {
		return x.DialogId
	}
	return ""
}

func (x *MessageFeedback) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageFeedback) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *MessageFeedback) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *MessageFeedback) GetPts() int32 {
	if x != nil {
		return x.Pts
	}
	return 0
}

func (x *MessageFeedback) GetChatTypeId() ChatType {
	if x != nil {
		return x.ChatTypeId
	}
	return ChatType_CT_USE
}

func (x *MessageFeedback) GetMessageTypeId() MessageType {
	if x != nil {
		return x.MessageTypeId
	}
	return MessageType_M_TEXT
}

func (x *MessageFeedback) GetFeedbackTypeId() MessageFeedbackType {
	if x != nil {
		return x.FeedbackTypeId
	}
	return MessageFeedbackType_MF_SEND
}

var File_message_feedback_proto protoreflect.FileDescriptor

var file_message_feedback_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x62, 0x61,
	0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69,
	0x6d, 0x1a, 0x0f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x12, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f,
	0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xc8, 0x02, 0x0a, 0x0f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x46,
	0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x69, 0x61, 0x6c, 0x6f,
	0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x69, 0x61, 0x6c,
	0x6f, 0x67, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x13, 0x0a, 0x05,
	0x74, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x6f, 0x49,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x70, 0x74, 0x73, 0x12, 0x33, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x69, 0x6d, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x63, 0x68,
	0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x12, 0x3c, 0x0a, 0x0f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6d, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x12, 0x46, 0x0a, 0x10, 0x66, 0x65, 0x65, 0x64, 0x62, 0x61,
	0x63, 0x6b, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6d, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0e,
	0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x42, 0x0c,
	0x5a, 0x0a, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6d, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_feedback_proto_rawDescOnce sync.Once
	file_message_feedback_proto_rawDescData = file_message_feedback_proto_rawDesc
)

func file_message_feedback_proto_rawDescGZIP() []byte {
	file_message_feedback_proto_rawDescOnce.Do(func() {
		file_message_feedback_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_feedback_proto_rawDescData)
	})
	return file_message_feedback_proto_rawDescData
}

var file_message_feedback_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_feedback_proto_goTypes = []interface{}{
	(*MessageFeedback)(nil),  // 0: protoim.MessageFeedback
	(ChatType)(0),            // 1: protoim.ChatType
	(MessageType)(0),         // 2: protoim.MessageType
	(MessageFeedbackType)(0), // 3: protoim.MessageFeedbackType
}
var file_message_feedback_proto_depIdxs = []int32{
	1, // 0: protoim.MessageFeedback.chat_type_id:type_name -> protoim.ChatType
	2, // 1: protoim.MessageFeedback.message_type_id:type_name -> protoim.MessageType
	3, // 2: protoim.MessageFeedback.feedback_type_id:type_name -> protoim.MessageFeedbackType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_message_feedback_proto_init() }
func file_message_feedback_proto_init() {
	if File_message_feedback_proto != nil {
		return
	}
	file_chat_type_proto_init()
	file_message_type_proto_init()
	file_message_feedback_type_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_message_feedback_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageFeedback); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_feedback_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_feedback_proto_goTypes,
		DependencyIndexes: file_message_feedback_proto_depIdxs,
		MessageInfos:      file_message_feedback_proto_msgTypes,
	}.Build()
	File_message_feedback_proto = out.File
	file_message_feedback_proto_rawDesc = nil
	file_message_feedback_proto_goTypes = nil
	file_message_feedback_proto_depIdxs = nil
}
