// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: message_feedback_type.proto

package protoim

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 反馈消息类型
type MessageFeedbackType int32

const (
	MessageFeedbackType_MF_SEND     MessageFeedbackType = 0 // 消息-已发送到服务器
	MessageFeedbackType_MF_RECEIVE  MessageFeedbackType = 1 // 消息-已接收(已读)
	MessageFeedbackType_MF_WITHDRAW MessageFeedbackType = 2 // 消息-已撤回
)

// Enum value maps for MessageFeedbackType.
var (
	MessageFeedbackType_name = map[int32]string{
		0: "MF_SEND",
		1: "MF_RECEIVE",
		2: "MF_WITHDRAW",
	}
	MessageFeedbackType_value = map[string]int32{
		"MF_SEND":     0,
		"MF_RECEIVE":  1,
		"MF_WITHDRAW": 2,
	}
)

func (x MessageFeedbackType) Enum() *MessageFeedbackType {
	p := new(MessageFeedbackType)
	*p = x
	return p
}

func (x MessageFeedbackType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageFeedbackType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_feedback_type_proto_enumTypes[0].Descriptor()
}

func (MessageFeedbackType) Type() protoreflect.EnumType {
	return &file_message_feedback_type_proto_enumTypes[0]
}

func (x MessageFeedbackType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageFeedbackType.Descriptor instead.
func (MessageFeedbackType) EnumDescriptor() ([]byte, []int) {
	return file_message_feedback_type_proto_rawDescGZIP(), []int{0}
}

var File_message_feedback_type_proto protoreflect.FileDescriptor

var file_message_feedback_type_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x62, 0x61,
	0x63, 0x6b, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6d, 0x2a, 0x43, 0x0a, 0x13, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a,
	0x07, 0x4d, 0x46, 0x5f, 0x53, 0x45, 0x4e, 0x44, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x4d, 0x46,
	0x5f, 0x52, 0x45, 0x43, 0x45, 0x49, 0x56, 0x45, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x46,
	0x5f, 0x57, 0x49, 0x54, 0x48, 0x44, 0x52, 0x41, 0x57, 0x10, 0x02, 0x42, 0x0c, 0x5a, 0x0a, 0x2e,
	0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_message_feedback_type_proto_rawDescOnce sync.Once
	file_message_feedback_type_proto_rawDescData = file_message_feedback_type_proto_rawDesc
)

func file_message_feedback_type_proto_rawDescGZIP() []byte {
	file_message_feedback_type_proto_rawDescOnce.Do(func() {
		file_message_feedback_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_feedback_type_proto_rawDescData)
	})
	return file_message_feedback_type_proto_rawDescData
}

var file_message_feedback_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_feedback_type_proto_goTypes = []interface{}{
	(MessageFeedbackType)(0), // 0: protoim.MessageFeedbackType
}
var file_message_feedback_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_feedback_type_proto_init() }
func file_message_feedback_type_proto_init() {
	if File_message_feedback_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_feedback_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_feedback_type_proto_goTypes,
		DependencyIndexes: file_message_feedback_type_proto_depIdxs,
		EnumInfos:         file_message_feedback_type_proto_enumTypes,
	}.Build()
	File_message_feedback_type_proto = out.File
	file_message_feedback_type_proto_rawDesc = nil
	file_message_feedback_type_proto_goTypes = nil
	file_message_feedback_type_proto_depIdxs = nil
}
