// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: message_red_packet.proto

package protoim

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 红包消息
type MessageRedPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MessageRedPacket) Reset() {
	*x = MessageRedPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_red_packet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageRedPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRedPacket) ProtoMessage() {}

func (x *MessageRedPacket) ProtoReflect() protoreflect.Message {
	mi := &file_message_red_packet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRedPacket.ProtoReflect.Descriptor instead.
func (*MessageRedPacket) Descriptor() ([]byte, []int) {
	return file_message_red_packet_proto_rawDescGZIP(), []int{0}
}

var File_message_red_packet_proto protoreflect.FileDescriptor

var file_message_red_packet_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x65, 0x64, 0x5f, 0x70, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x69, 0x6d, 0x22, 0x12, 0x0a, 0x10, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x64, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x3b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x69, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_red_packet_proto_rawDescOnce sync.Once
	file_message_red_packet_proto_rawDescData = file_message_red_packet_proto_rawDesc
)

func file_message_red_packet_proto_rawDescGZIP() []byte {
	file_message_red_packet_proto_rawDescOnce.Do(func() {
		file_message_red_packet_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_red_packet_proto_rawDescData)
	})
	return file_message_red_packet_proto_rawDescData
}

var file_message_red_packet_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_red_packet_proto_goTypes = []interface{}{
	(*MessageRedPacket)(nil), // 0: protoim.MessageRedPacket
}
var file_message_red_packet_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_red_packet_proto_init() }
func file_message_red_packet_proto_init() {
	if File_message_red_packet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_red_packet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageRedPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_red_packet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_red_packet_proto_goTypes,
		DependencyIndexes: file_message_red_packet_proto_depIdxs,
		MessageInfos:      file_message_red_packet_proto_msgTypes,
	}.Build()
	File_message_red_packet_proto = out.File
	file_message_red_packet_proto_rawDesc = nil
	file_message_red_packet_proto_goTypes = nil
	file_message_red_packet_proto_depIdxs = nil
}
