// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: message_request.proto

package protoim

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息相关(客户端发送-服务端接收)-请求
type MessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocalMsgId    string      `protobuf:"bytes,1,opt,name=local_msg_id,json=localMsgId,proto3" json:"local_msg_id,omitempty"`                                    // 客户端本地的消息ID(用于客户校验)(客户端生成)
	FromId        string      `protobuf:"bytes,2,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`                                                  // 发送者(用户ID)
	ChatTypeId    ChatType    `protobuf:"varint,3,opt,name=chat_type_id,json=chatTypeId,proto3,enum=protoim.ChatType" json:"chat_type_id,omitempty"`             // 私聊还是群聊
	ToId          string      `protobuf:"bytes,4,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`                                                        // 接收者(用户ID/群ID)
	MessageTypeId MessageType `protobuf:"varint,5,opt,name=message_type_id,json=messageTypeId,proto3,enum=protoim.MessageType" json:"message_type_id,omitempty"` // 消息类型
	Content       string      `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`                                                              // 消息的内容
}

func (x *MessageRequest) Reset() {
	*x = MessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRequest) ProtoMessage() {}

func (x *MessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRequest.ProtoReflect.Descriptor instead.
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return file_message_request_proto_rawDescGZIP(), []int{0}
}

func (x *MessageRequest) GetLocalMsgId() string {
	if x != nil {
		return x.LocalMsgId
	}
	return ""
}

func (x *MessageRequest) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *MessageRequest) GetChatTypeId() ChatType {
	if x != nil {
		return x.ChatTypeId
	}
	return ChatType_USE_CHAT
}

func (x *MessageRequest) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *MessageRequest) GetMessageTypeId() MessageType {
	if x != nil {
		return x.MessageTypeId
	}
	return MessageType_TEXT_TYPE
}

func (x *MessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_message_request_proto protoreflect.FileDescriptor

var file_message_request_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6d,
	0x1a, 0x0f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x12, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xed, 0x01, 0x0a, 0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0c, 0x6c, 0x6f, 0x63, 0x61,
	0x6c, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x72,
	0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x72, 0x6f,
	0x6d, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x69, 0x6d, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x63, 0x68,
	0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x12, 0x13, 0x0a, 0x05, 0x74, 0x6f, 0x5f, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x6f, 0x49, 0x64, 0x12, 0x3c, 0x0a,
	0x0f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6d,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0d, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x69, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_request_proto_rawDescOnce sync.Once
	file_message_request_proto_rawDescData = file_message_request_proto_rawDesc
)

func file_message_request_proto_rawDescGZIP() []byte {
	file_message_request_proto_rawDescOnce.Do(func() {
		file_message_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_request_proto_rawDescData)
	})
	return file_message_request_proto_rawDescData
}

var file_message_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_request_proto_goTypes = []interface{}{
	(*MessageRequest)(nil), // 0: protoim.MessageRequest
	(ChatType)(0),          // 1: protoim.ChatType
	(MessageType)(0),       // 2: protoim.MessageType
}
var file_message_request_proto_depIdxs = []int32{
	1, // 0: protoim.MessageRequest.chat_type_id:type_name -> protoim.ChatType
	2, // 1: protoim.MessageRequest.message_type_id:type_name -> protoim.MessageType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_message_request_proto_init() }
func file_message_request_proto_init() {
	if File_message_request_proto != nil {
		return
	}
	file_chat_type_proto_init()
	file_message_type_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_message_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_request_proto_goTypes,
		DependencyIndexes: file_message_request_proto_depIdxs,
		MessageInfos:      file_message_request_proto_msgTypes,
	}.Build()
	File_message_request_proto = out.File
	file_message_request_proto_rawDesc = nil
	file_message_request_proto_goTypes = nil
	file_message_request_proto_depIdxs = nil
}
