// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: message_response.proto

package protoim

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId         string      `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`                                                     // 消息ID(服务端生成)
	LocalMsgId    string      `protobuf:"bytes,2,opt,name=local_msg_id,json=localMsgId,proto3" json:"local_msg_id,omitempty"`                                    // 客户端本地的消息ID(用于客户校验)(客户端生成)
	Pts           int32       `protobuf:"varint,3,opt,name=pts,proto3" json:"pts,omitempty"`                                                                     // 当前会话的序列ID(可用于排序)(唯一值)(服务端生成)
	FromId        string      `protobuf:"bytes,4,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`                                                  // 发送者(用户ID)
	ChatTypeId    ChatType    `protobuf:"varint,5,opt,name=chat_type_id,json=chatTypeId,proto3,enum=protoim.ChatType" json:"chat_type_id,omitempty"`             // 私聊还是群聊
	ToId          string      `protobuf:"bytes,6,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`                                                        // 接收者(用户ID/群ID)
	MessageTypeId MessageType `protobuf:"varint,7,opt,name=message_type_id,json=messageTypeId,proto3,enum=protoim.MessageType" json:"message_type_id,omitempty"` // 消息类型
	Content       string      `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`                                                              // 消息的内容
	DataTime      int64       `protobuf:"varint,9,opt,name=data_time,json=dataTime,proto3" json:"data_time,omitempty"`                                           // 发送时间戳(以服务端接收到的时间为准)
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_message_response_proto_rawDescGZIP(), []int{0}
}

func (x *MessageResponse) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *MessageResponse) GetLocalMsgId() string {
	if x != nil {
		return x.LocalMsgId
	}
	return ""
}

func (x *MessageResponse) GetPts() int32 {
	if x != nil {
		return x.Pts
	}
	return 0
}

func (x *MessageResponse) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *MessageResponse) GetChatTypeId() ChatType {
	if x != nil {
		return x.ChatTypeId
	}
	return ChatType_USE_CHAT
}

func (x *MessageResponse) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *MessageResponse) GetMessageTypeId() MessageType {
	if x != nil {
		return x.MessageTypeId
	}
	return MessageType_TEXT_TYPE
}

func (x *MessageResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageResponse) GetDataTime() int64 {
	if x != nil {
		return x.DataTime
	}
	return 0
}

var File_message_response_proto protoreflect.FileDescriptor

var file_message_response_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69,
	0x6d, 0x1a, 0x0f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x12, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb4, 0x02, 0x0a, 0x0f, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x73,
	0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49,
	0x64, 0x12, 0x20, 0x0a, 0x0c, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x4d, 0x73,
	0x67, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x70, 0x74, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x33,
	0x0a, 0x0c, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6d, 0x2e, 0x43,
	0x68, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x63, 0x68, 0x61, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x49, 0x64, 0x12, 0x13, 0x0a, 0x05, 0x74, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x6f, 0x49, 0x64, 0x12, 0x3c, 0x0a, 0x0f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6d, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x0c, 0x5a,
	0x0a, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_message_response_proto_rawDescOnce sync.Once
	file_message_response_proto_rawDescData = file_message_response_proto_rawDesc
)

func file_message_response_proto_rawDescGZIP() []byte {
	file_message_response_proto_rawDescOnce.Do(func() {
		file_message_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_response_proto_rawDescData)
	})
	return file_message_response_proto_rawDescData
}

var file_message_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_response_proto_goTypes = []interface{}{
	(*MessageResponse)(nil), // 0: protoim.MessageResponse
	(ChatType)(0),           // 1: protoim.ChatType
	(MessageType)(0),        // 2: protoim.MessageType
}
var file_message_response_proto_depIdxs = []int32{
	1, // 0: protoim.MessageResponse.chat_type_id:type_name -> protoim.ChatType
	2, // 1: protoim.MessageResponse.message_type_id:type_name -> protoim.MessageType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_message_response_proto_init() }
func file_message_response_proto_init() {
	if File_message_response_proto != nil {
		return
	}
	file_chat_type_proto_init()
	file_message_type_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_message_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_response_proto_goTypes,
		DependencyIndexes: file_message_response_proto_depIdxs,
		MessageInfos:      file_message_response_proto_msgTypes,
	}.Build()
	File_message_response_proto = out.File
	file_message_response_proto_rawDesc = nil
	file_message_response_proto_goTypes = nil
	file_message_response_proto_depIdxs = nil
}
