// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: message_type.proto

package protoim

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息类型
type MessageType int32

const (
	MessageType_M_TEXT       MessageType = 0 // 文本消息
	MessageType_M_IMAGE      MessageType = 1 // 图片消息
	MessageType_M_FILE       MessageType = 2 // 文件消息
	MessageType_M_VOICE      MessageType = 3 // 语音文件消息
	MessageType_M_VIDEO      MessageType = 4 // 视频文件消息
	MessageType_M_MAP        MessageType = 5 // 地理位置消息
	MessageType_M_RED_PACKET MessageType = 6 // 红包消息
	MessageType_M_TIPS       MessageType = 7 // 提示消息
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "M_TEXT",
		1: "M_IMAGE",
		2: "M_FILE",
		3: "M_VOICE",
		4: "M_VIDEO",
		5: "M_MAP",
		6: "M_RED_PACKET",
		7: "M_TIPS",
	}
	MessageType_value = map[string]int32{
		"M_TEXT":       0,
		"M_IMAGE":      1,
		"M_FILE":       2,
		"M_VOICE":      3,
		"M_VIDEO":      4,
		"M_MAP":        5,
		"M_RED_PACKET": 6,
		"M_TIPS":       7,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_type_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_message_type_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_message_type_proto_rawDescGZIP(), []int{0}
}

var File_message_type_proto protoreflect.FileDescriptor

var file_message_type_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6d, 0x2a, 0x75, 0x0a,
	0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06,
	0x4d, 0x5f, 0x54, 0x45, 0x58, 0x54, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x5f, 0x49, 0x4d,
	0x41, 0x47, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x5f, 0x46, 0x49, 0x4c, 0x45, 0x10,
	0x02, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x5f, 0x56, 0x4f, 0x49, 0x43, 0x45, 0x10, 0x03, 0x12, 0x0b,
	0x0a, 0x07, 0x4d, 0x5f, 0x56, 0x49, 0x44, 0x45, 0x4f, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x4d,
	0x5f, 0x4d, 0x41, 0x50, 0x10, 0x05, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x5f, 0x52, 0x45, 0x44, 0x5f,
	0x50, 0x41, 0x43, 0x4b, 0x45, 0x54, 0x10, 0x06, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x5f, 0x54, 0x49,
	0x50, 0x53, 0x10, 0x07, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x69, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_type_proto_rawDescOnce sync.Once
	file_message_type_proto_rawDescData = file_message_type_proto_rawDesc
)

func file_message_type_proto_rawDescGZIP() []byte {
	file_message_type_proto_rawDescOnce.Do(func() {
		file_message_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_type_proto_rawDescData)
	})
	return file_message_type_proto_rawDescData
}

var file_message_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_type_proto_goTypes = []interface{}{
	(MessageType)(0), // 0: protoim.MessageType
}
var file_message_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_type_proto_init() }
func file_message_type_proto_init() {
	if File_message_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_type_proto_goTypes,
		DependencyIndexes: file_message_type_proto_depIdxs,
		EnumInfos:         file_message_type_proto_enumTypes,
	}.Build()
	File_message_type_proto = out.File
	file_message_type_proto_rawDesc = nil
	file_message_type_proto_goTypes = nil
	file_message_type_proto_depIdxs = nil
}
