// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: update_user_friend_info.proto

package protoim

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateUserFriendInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag  string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Uid  int32  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UpdateUserFriendInfo) Reset() {
	*x = UpdateUserFriendInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_update_user_friend_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUserFriendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserFriendInfo) ProtoMessage() {}

func (x *UpdateUserFriendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_update_user_friend_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserFriendInfo.ProtoReflect.Descriptor instead.
func (*UpdateUserFriendInfo) Descriptor() ([]byte, []int) {
	return file_update_user_friend_info_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateUserFriendInfo) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *UpdateUserFriendInfo) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UpdateUserFriendInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_update_user_friend_info_proto protoreflect.FileDescriptor

var file_update_user_friend_info_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x66, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6d, 0x22, 0x4e, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74,
	0x61, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x3b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_update_user_friend_info_proto_rawDescOnce sync.Once
	file_update_user_friend_info_proto_rawDescData = file_update_user_friend_info_proto_rawDesc
)

func file_update_user_friend_info_proto_rawDescGZIP() []byte {
	file_update_user_friend_info_proto_rawDescOnce.Do(func() {
		file_update_user_friend_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_update_user_friend_info_proto_rawDescData)
	})
	return file_update_user_friend_info_proto_rawDescData
}

var file_update_user_friend_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_update_user_friend_info_proto_goTypes = []interface{}{
	(*UpdateUserFriendInfo)(nil), // 0: protoim.UpdateUserFriendInfo
}
var file_update_user_friend_info_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_update_user_friend_info_proto_init() }
func file_update_user_friend_info_proto_init() {
	if File_update_user_friend_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_update_user_friend_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUserFriendInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_update_user_friend_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_update_user_friend_info_proto_goTypes,
		DependencyIndexes: file_update_user_friend_info_proto_depIdxs,
		MessageInfos:      file_update_user_friend_info_proto_msgTypes,
	}.Build()
	File_update_user_friend_info_proto = out.File
	file_update_user_friend_info_proto_rawDesc = nil
	file_update_user_friend_info_proto_goTypes = nil
	file_update_user_friend_info_proto_depIdxs = nil
}
