// source: message_request.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var chat_type_pb = require('./chat_type_pb.js');
goog.object.extend(proto, chat_type_pb);
var message_type_pb = require('./message_type_pb.js');
goog.object.extend(proto, message_type_pb);
var message_entity_uri_pb = require('./message_entity_uri_pb.js');
goog.object.extend(proto, message_entity_uri_pb);
var message_media_pb = require('./message_media_pb.js');
goog.object.extend(proto, message_media_pb);
goog.exportSymbol('proto.protoim.MessageRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.protoim.MessageRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.protoim.MessageRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.protoim.MessageRequest.displayName = 'proto.protoim.MessageRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.protoim.MessageRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.protoim.MessageRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.protoim.MessageRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.protoim.MessageRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    conversationId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    localMsgId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    fromId: jspb.Message.getFieldWithDefault(msg, 3, ""),
    toId: jspb.Message.getFieldWithDefault(msg, 4, ""),
    chatTypeId: jspb.Message.getFieldWithDefault(msg, 5, 0),
    messageTypeId: jspb.Message.getFieldWithDefault(msg, 6, 0),
    content: jspb.Message.getFieldWithDefault(msg, 7, ""),
    entity: (f = msg.getEntity()) && message_entity_uri_pb.MessageEntityUri.toObject(includeInstance, f),
    media: (f = msg.getMedia()) && message_media_pb.MessageMedia.toObject(includeInstance, f),
    thumbnail: (f = msg.getThumbnail()) && message_media_pb.MessageMedia.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.protoim.MessageRequest}
 */
proto.protoim.MessageRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.protoim.MessageRequest;
  return proto.protoim.MessageRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.protoim.MessageRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.protoim.MessageRequest}
 */
proto.protoim.MessageRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setConversationId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setLocalMsgId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setFromId(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setToId(value);
      break;
    case 5:
      var value = /** @type {!proto.protoim.ChatType} */ (reader.readEnum());
      msg.setChatTypeId(value);
      break;
    case 6:
      var value = /** @type {!proto.protoim.MessageType} */ (reader.readEnum());
      msg.setMessageTypeId(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setContent(value);
      break;
    case 8:
      var value = new message_entity_uri_pb.MessageEntityUri;
      reader.readMessage(value,message_entity_uri_pb.MessageEntityUri.deserializeBinaryFromReader);
      msg.setEntity(value);
      break;
    case 9:
      var value = new message_media_pb.MessageMedia;
      reader.readMessage(value,message_media_pb.MessageMedia.deserializeBinaryFromReader);
      msg.setMedia(value);
      break;
    case 10:
      var value = new message_media_pb.MessageMedia;
      reader.readMessage(value,message_media_pb.MessageMedia.deserializeBinaryFromReader);
      msg.setThumbnail(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.protoim.MessageRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.protoim.MessageRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.protoim.MessageRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.protoim.MessageRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getConversationId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLocalMsgId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getFromId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getToId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getChatTypeId();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getMessageTypeId();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
  f = message.getContent();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getEntity();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      message_entity_uri_pb.MessageEntityUri.serializeBinaryToWriter
    );
  }
  f = message.getMedia();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      message_media_pb.MessageMedia.serializeBinaryToWriter
    );
  }
  f = message.getThumbnail();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      message_media_pb.MessageMedia.serializeBinaryToWriter
    );
  }
};


/**
 * optional string conversation_id = 1;
 * @return {string}
 */
proto.protoim.MessageRequest.prototype.getConversationId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.protoim.MessageRequest} returns this
 */
proto.protoim.MessageRequest.prototype.setConversationId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string local_msg_id = 2;
 * @return {string}
 */
proto.protoim.MessageRequest.prototype.getLocalMsgId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.protoim.MessageRequest} returns this
 */
proto.protoim.MessageRequest.prototype.setLocalMsgId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string from_id = 3;
 * @return {string}
 */
proto.protoim.MessageRequest.prototype.getFromId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.protoim.MessageRequest} returns this
 */
proto.protoim.MessageRequest.prototype.setFromId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string to_id = 4;
 * @return {string}
 */
proto.protoim.MessageRequest.prototype.getToId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.protoim.MessageRequest} returns this
 */
proto.protoim.MessageRequest.prototype.setToId = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional ChatType chat_type_id = 5;
 * @return {!proto.protoim.ChatType}
 */
proto.protoim.MessageRequest.prototype.getChatTypeId = function() {
  return /** @type {!proto.protoim.ChatType} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.protoim.ChatType} value
 * @return {!proto.protoim.MessageRequest} returns this
 */
proto.protoim.MessageRequest.prototype.setChatTypeId = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * optional MessageType message_type_id = 6;
 * @return {!proto.protoim.MessageType}
 */
proto.protoim.MessageRequest.prototype.getMessageTypeId = function() {
  return /** @type {!proto.protoim.MessageType} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {!proto.protoim.MessageType} value
 * @return {!proto.protoim.MessageRequest} returns this
 */
proto.protoim.MessageRequest.prototype.setMessageTypeId = function(value) {
  return jspb.Message.setProto3EnumField(this, 6, value);
};


/**
 * optional string content = 7;
 * @return {string}
 */
proto.protoim.MessageRequest.prototype.getContent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.protoim.MessageRequest} returns this
 */
proto.protoim.MessageRequest.prototype.setContent = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional MessageEntityUri entity = 8;
 * @return {?proto.protoim.MessageEntityUri}
 */
proto.protoim.MessageRequest.prototype.getEntity = function() {
  return /** @type{?proto.protoim.MessageEntityUri} */ (
    jspb.Message.getWrapperField(this, message_entity_uri_pb.MessageEntityUri, 8));
};


/**
 * @param {?proto.protoim.MessageEntityUri|undefined} value
 * @return {!proto.protoim.MessageRequest} returns this
*/
proto.protoim.MessageRequest.prototype.setEntity = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.protoim.MessageRequest} returns this
 */
proto.protoim.MessageRequest.prototype.clearEntity = function() {
  return this.setEntity(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.protoim.MessageRequest.prototype.hasEntity = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional MessageMedia media = 9;
 * @return {?proto.protoim.MessageMedia}
 */
proto.protoim.MessageRequest.prototype.getMedia = function() {
  return /** @type{?proto.protoim.MessageMedia} */ (
    jspb.Message.getWrapperField(this, message_media_pb.MessageMedia, 9));
};


/**
 * @param {?proto.protoim.MessageMedia|undefined} value
 * @return {!proto.protoim.MessageRequest} returns this
*/
proto.protoim.MessageRequest.prototype.setMedia = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.protoim.MessageRequest} returns this
 */
proto.protoim.MessageRequest.prototype.clearMedia = function() {
  return this.setMedia(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.protoim.MessageRequest.prototype.hasMedia = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional MessageMedia thumbnail = 10;
 * @return {?proto.protoim.MessageMedia}
 */
proto.protoim.MessageRequest.prototype.getThumbnail = function() {
  return /** @type{?proto.protoim.MessageMedia} */ (
    jspb.Message.getWrapperField(this, message_media_pb.MessageMedia, 10));
};


/**
 * @param {?proto.protoim.MessageMedia|undefined} value
 * @return {!proto.protoim.MessageRequest} returns this
*/
proto.protoim.MessageRequest.prototype.setThumbnail = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.protoim.MessageRequest} returns this
 */
proto.protoim.MessageRequest.prototype.clearThumbnail = function() {
  return this.setThumbnail(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.protoim.MessageRequest.prototype.hasThumbnail = function() {
  return jspb.Message.getField(this, 10) != null;
};


goog.object.extend(exports, proto.protoim);
