// source: update_friend.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var user_info_pb = require('./user_info_pb.js');
goog.object.extend(proto, user_info_pb);
var update_friend_type_pb = require('./update_friend_type_pb.js');
goog.object.extend(proto, update_friend_type_pb);
goog.exportSymbol('proto.protoim.UpdateFriend', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.protoim.UpdateFriend = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.protoim.UpdateFriend, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.protoim.UpdateFriend.displayName = 'proto.protoim.UpdateFriend';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.protoim.UpdateFriend.prototype.toObject = function(opt_includeInstance) {
  return proto.protoim.UpdateFriend.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.protoim.UpdateFriend} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.protoim.UpdateFriend.toObject = function(includeInstance, msg) {
  var f, obj = {
    tag: jspb.Message.getFieldWithDefault(msg, 1, 0),
    user: (f = msg.getUser()) && user_info_pb.UserInfo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.protoim.UpdateFriend}
 */
proto.protoim.UpdateFriend.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.protoim.UpdateFriend;
  return proto.protoim.UpdateFriend.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.protoim.UpdateFriend} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.protoim.UpdateFriend}
 */
proto.protoim.UpdateFriend.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.protoim.UpdateFriendType} */ (reader.readEnum());
      msg.setTag(value);
      break;
    case 2:
      var value = new user_info_pb.UserInfo;
      reader.readMessage(value,user_info_pb.UserInfo.deserializeBinaryFromReader);
      msg.setUser(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.protoim.UpdateFriend.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.protoim.UpdateFriend.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.protoim.UpdateFriend} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.protoim.UpdateFriend.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTag();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getUser();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      user_info_pb.UserInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional UpdateFriendType tag = 1;
 * @return {!proto.protoim.UpdateFriendType}
 */
proto.protoim.UpdateFriend.prototype.getTag = function() {
  return /** @type {!proto.protoim.UpdateFriendType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.protoim.UpdateFriendType} value
 * @return {!proto.protoim.UpdateFriend} returns this
 */
proto.protoim.UpdateFriend.prototype.setTag = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional UserInfo user = 2;
 * @return {?proto.protoim.UserInfo}
 */
proto.protoim.UpdateFriend.prototype.getUser = function() {
  return /** @type{?proto.protoim.UserInfo} */ (
    jspb.Message.getWrapperField(this, user_info_pb.UserInfo, 2));
};


/**
 * @param {?proto.protoim.UserInfo|undefined} value
 * @return {!proto.protoim.UpdateFriend} returns this
*/
proto.protoim.UpdateFriend.prototype.setUser = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.protoim.UpdateFriend} returns this
 */
proto.protoim.UpdateFriend.prototype.clearUser = function() {
  return this.setUser(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.protoim.UpdateFriend.prototype.hasUser = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.protoim);
