// source: update_friends.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var update_friend_pb = require('./update_friend_pb.js');
goog.object.extend(proto, update_friend_pb);
goog.exportSymbol('proto.protoim.UpdateFriends', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.protoim.UpdateFriends = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.protoim.UpdateFriends.repeatedFields_, null);
};
goog.inherits(proto.protoim.UpdateFriends, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.protoim.UpdateFriends.displayName = 'proto.protoim.UpdateFriends';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.protoim.UpdateFriends.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.protoim.UpdateFriends.prototype.toObject = function(opt_includeInstance) {
  return proto.protoim.UpdateFriends.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.protoim.UpdateFriends} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.protoim.UpdateFriends.toObject = function(includeInstance, msg) {
  var f, obj = {
    usersList: jspb.Message.toObjectList(msg.getUsersList(),
    update_friend_pb.UpdateFriend.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.protoim.UpdateFriends}
 */
proto.protoim.UpdateFriends.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.protoim.UpdateFriends;
  return proto.protoim.UpdateFriends.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.protoim.UpdateFriends} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.protoim.UpdateFriends}
 */
proto.protoim.UpdateFriends.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new update_friend_pb.UpdateFriend;
      reader.readMessage(value,update_friend_pb.UpdateFriend.deserializeBinaryFromReader);
      msg.addUsers(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.protoim.UpdateFriends.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.protoim.UpdateFriends.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.protoim.UpdateFriends} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.protoim.UpdateFriends.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUsersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      update_friend_pb.UpdateFriend.serializeBinaryToWriter
    );
  }
};


/**
 * repeated UpdateFriend users = 1;
 * @return {!Array<!proto.protoim.UpdateFriend>}
 */
proto.protoim.UpdateFriends.prototype.getUsersList = function() {
  return /** @type{!Array<!proto.protoim.UpdateFriend>} */ (
    jspb.Message.getRepeatedWrapperField(this, update_friend_pb.UpdateFriend, 1));
};


/**
 * @param {!Array<!proto.protoim.UpdateFriend>} value
 * @return {!proto.protoim.UpdateFriends} returns this
*/
proto.protoim.UpdateFriends.prototype.setUsersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.protoim.UpdateFriend=} opt_value
 * @param {number=} opt_index
 * @return {!proto.protoim.UpdateFriend}
 */
proto.protoim.UpdateFriends.prototype.addUsers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.protoim.UpdateFriend, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.protoim.UpdateFriends} returns this
 */
proto.protoim.UpdateFriends.prototype.clearUsersList = function() {
  return this.setUsersList([]);
};


goog.object.extend(exports, proto.protoim);
